[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "is4010-final-password-manager"
version = "0.1.0"
description = "Local password manager CLI for IS4010 final project"
readme = "README.md"
requires-python = ">=3.10"

[project.urls]
homepage = "https://github.com/leah900/is4010-final-password-manager"
